node {
    /* kode final */

    stage('Build') {
        docker.image('python:2-alpine').inside {
            checkout scm
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            checkout scm
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }

    stage('Deploy') {
        checkout scm
        sh 'docker run -v "$(pwd):/src/" cdrx/pyinstaller-linux "pyinstaller --onefile sources/add2vals.py"'
        
        sshagent (credentials: ['ubuntu-ec2']) {
                // sh 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T dist/add2vals ubuntu@18.139.114.24:/home/ubuntu/add2vals'
                sh 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@18.139.114.24 && chmod +x /home/ubuntu/add2vals && ./home/ubuntu/add2vals 6 6'
        }
    }
}
