node {
    /* Requires the Docker Pipeline plugin to be installed */
    docker.image('python:2-alpine').inside {
        stage('Build') {
            sh 'cd /home/jenkins/simple-python-pyinstaller-app'
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    docker.image('qnib/pytest').inside {
        stage('Test') {
            sh 'pwd'
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }
}
